version: '3'
services:

    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_DB=DNC_chal_db
            - POSTGRES_USER=DNC_chal_db
            - POSTGRES_PASSWORD=DNC_chal_db
            - DJANGO_SETTINGS_MODULE=mysite.settings_docker
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/code:Z
        depends_on:
            - db
        ports:
            - "8000:8000"

    db:
        image: postgres:13
        environment:
            - POSTGRES_DB=DNC_chal_db
            - POSTGRES_USER=DNC_chal_db
            - POSTGRES_PASSWORD=DNC_chal_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
